---
- name: Exercise 5a
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Run the show interfaces terse command
      junipernetworks.junos.junos_command: 
        commands: show interfaces terse
      register: interfaces_output

    - ansible.builtin.debug:
        var: interfaces_output 

