---
- name: Exercise 2
  hosts: arista
  gather_facts: False
  tasks:  
    - name: Executing command
      cisco.ios.ios_command:
        commands: show ip arp
      register: show_ip_arp_output

    - name: Print output of filter
      debug:
        msg: "{{ show_ip_arp_output.stdout[0] | show_ip_arp }}"
