---
- name: Exercise 4a
  hosts: cisco6
  gather_facts: False
  tasks:
    - name: Clear logging buffer
      cisco.ios.ios_command:
        commands:
          - command: clear logging
            prompt: confirm
            answer: '\r'
      register: clear_log_output

    - name: Print clear log output
      ansible.builtin.debug:
        var: clear_log_output
