---
- name: Exercise 1b
  hosts: cisco:arista:juniper
  gather_facts: False
  tasks:
    - name: Execute show ip arp on EOS
      arista.eos.eos_command:
        commands: show ip arp
      register: show_ip_arp_output_eos
      when: ansible_network_os == 'eos'
      tags:
        - eos

    - name: Execute show ip arp on IOS
      cisco.ios.ios_command:
        commands: show ip arp
      register: show_ip_arp_output_ios
      when: ansible_network_os == 'ios'
      tags:
        - ios

    - name: Execute show arp on Junos
      junipernetworks.junos.junos_command:
        commands: show arp
      register: show_arp_output_junos
      when: ansible_network_os == 'junos'
      tags:
        - junos
  
    - name: Print EOS output
      debug:
        var: show_ip_arp_output_eos
      when: ansible_network_os == 'eos'
      tags:
        - eos

