---
- name: Use SSH keys for authentication
  hosts: cisco1:cisco2
  gather_facts: False
  tasks:
    - name: Run show users command
      cisco.ios.ios_command:
        commands: show users
      register: output

    - name: View connected users
      debug:
        var: output.stdout[0]

    - name: Verify connected users
      ansible.builtin.assert:
        that:
          - '"student1" in output.stdout[0]'
