---
- name: Arista5 Play
  hosts: arista5
  gather_facts: True
  gather_subset: all
  vars_files: my_vars.yaml

  tasks:
    - name: Print arista5 ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print arista5 ansible_facts.net_all_ipv4_addresses
      ansible.builtin.debug:
        var: ansible_facts.net_all_ipv4_addresses

    - name: Print arista5 ansible_network_os
      ansible.builtin.debug:
        var: ansible_network_os

    - name: Print arista5 ansible_host
      ansible.builtin.debug:
        var: ansible_host
  
    - name: Print arista5 desired_eos_version
      ansible.builtin.debug:
        var: desired_eos_version

    - name: Set device_hostname
      ansible.builtin.set_fact:
        device_hostname: "{{ inventory_hostname }}.lab.io"

    - name: Print device_hostname
      ansible.builtin.debug:
        var: device_hostname
