---
- name: Exercise 1
  hosts: cisco:arista:nxos:juniper
  gather_facts: True
  tasks:
    - name: IOS Config
      cisco.ios.ios_config:
        lines:
          - "ip name-server {{ dns_server1 }}"
          - "ip name-server {{ dns_server2 }}"
          - "ip domain name {{ domain_name }}"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"
        save_when: changed
      when: ansible_facts.net_iostype is defined and ansible_facts.net_iostype == "IOS"

    - name: IOS XE Config
      cisco.ios.ios_config:
        lines:
          - "ip name-server {{ dns_server1 }} {{ dns_server2 }}"
          - "ip domain name {{ domain_name }}"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"  
        save_when: changed
      when: ansible_facts.net_iostype is defined and ansible_facts.net_iostype == "IOS-XE"

    - name: EOS Config
      arista.eos.eos_config:
        lines:
          - "ip name-server {{ dns_server1 }}"
          - "ip name-server {{ dns_server2 }}"
          - "ip domain-name {{ domain_name }}"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"
        save_when: changed
      when: 'ansible_network_os == "eos"'

    - name: NXOS Config
      cisco.nxos.nxos_config:
        lines:
          - "ip domain-name {{ domain_name }}"
          - "ip name-server {{ dns_server1 }} {{ dns_server2 }}"
          - "ntp server {{ ntp_server1 }} use-vrf managmenet"
          - "ntp server {{ ntp_server2 }} use-vrf default"
        save_when: changed
      when: 'ansible_network_os == "nxos"'

    - name: Juniper Config
      junipernetworks.junos.junos_config:
        lines:
          - "set system name-server {{ dns_server1 }}"
          - "set system name-server {{ dns_server2 }}"
          - "set system domain-name {{ domain_name }}"
          - "set system ntp server {{ ntp_server1 }}"
          - "set system ntp server {{ ntp_server2 }}"
      when: 'ansible_network_os == "junos"'
        
