---
- name: Exercise 3b
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Get show version and show lldp neighbors output
      cisco.nxos.nxos_command:
        commands: 
          - show version
          - show lldp neighbors 
      register: show_output

    - debug:
        var: show_output['stdout_lines'][1]
