---
- name: Exercise2
  hosts: arista
  gather_facts: False
  tasks:
    - block:
        - name: Login using invalid password
          vars:
            ansible_ssh_pass: "Password123"
          arista.eos.eos_config: 
            lines:
              - "ip name-server {{ dns_server1 }}"
              - "ip name-server {{ dns_server2 }}"

      rescue:
        - name: Login again using good password
          vars:
            ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
          arista.eos.eos_config:
            lines: 
              - "ip name-server {{ dns_server1 }}"
              - "ip name-server {{ dns_server2 }}"
