---
- name: Exercise 4
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Generate interface config
      ansible.builtin.template:
        src: interfaces.j2
        dest: "./CFGS/{{ inventory_hostname }}/01-{{ inventory_hostname }}-intf.txt"

    - name: Generate BGP config
      ansible.builtin.template:
        src: bgp.j2
        dest: "./CFGS/{{ inventory_hostname }}/02-{{ inventory_hostname }}-bgp.txt"

    - name: Merge into one config file
      ansible.builtin.assemble:
        src: "./CFGS/{{ inventory_hostname }}/"
        dest: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Deploy configs to devices
      cisco.nxos.nxos_config:
        src: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Verify BGP State
      cisco.nxos.nxos_command:
        commands: show ip bgp summary
      register: output
      tags: verify

    - name: Show BGP Session
      debug:
        var: output.stdout_lines[0]
      tags: verify
