---
- name: Exercise 3
  hosts: cisco1:cisco2
  gather_facts: False
  
  tasks:
    - cisco.ios.ios_command:
        commands: show lldp neighbors
      register: show_lldp_neighbors

    - name: Extract lines from output 
      set_fact:
          lldp: "{{ show_lldp_neighbors['stdout_lines'][0] }}"

    - name: Find LLDP entry
      set_fact:
        lldp_entry: "{{ item }}"
      loop: "{{ lldp }}"
      when: "'twb-sf-hpsw1' in item"

    - name: Extract from line
      set_fact:
        remote_device: "{{ lldp_entry.split()[0] }}"
        local_intf: "{{ lldp_entry.split()[1] }}"
        remote_intf: "{{ lldp_entry.split()[4] }}"

    - name: Print output
      debug:
        msg:
          - "Remote device: {{ remote_device }}"
          - "Local intf: {{ local_intf }}"
          - "Remote intf: {{ remote_intf }}"
