---
- name: Exercise 5
  hosts: nxos1:nxos2
  gather_facts: False
  tasks:
    - name: Generate Config
      template:
        src: nxos.j2
        dest: "./CFGS/{{ inventory_hostname }}/01-{{ inventory_hostname }}-config.txt"
