---
- name: Exercise 2a
  hosts: cisco
  gather_facts: False
  tasks:
    - name: Printing ASN
      ansible.builtin.debug:
        msg: "The ASN for host {{ inventory_hostname }} is {{ bgp_asn }}, the router-id is {{ bgp_router_id }}" 
